// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBi-PZkmAV2WSiwM_5QkpsHQXNXDQbnHXU',
    appId: '1:605318797673:web:489c4cd712390e4b9ec5f8',
    messagingSenderId: '605318797673',
    projectId: 'to-do-list-82f31',
    authDomain: 'to-do-list-82f31.firebaseapp.com',
    storageBucket: 'to-do-list-82f31.appspot.com',
    measurementId: 'G-ZN03FWH4GB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDQrcO6Nr4HFj3Cv3Jv9JL1Hg7BQSsMloE',
    appId: '1:605318797673:android:2af7154d13e00adf9ec5f8',
    messagingSenderId: '605318797673',
    projectId: 'to-do-list-82f31',
    storageBucket: 'to-do-list-82f31.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBmFOvXcLtgh5Rt4JicHVWYfNmVysrUoWI',
    appId: '1:605318797673:ios:eaff9dbfc8bbb2f79ec5f8',
    messagingSenderId: '605318797673',
    projectId: 'to-do-list-82f31',
    storageBucket: 'to-do-list-82f31.appspot.com',
    iosBundleId: 'com.example.toDoApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBmFOvXcLtgh5Rt4JicHVWYfNmVysrUoWI',
    appId: '1:605318797673:ios:d594df09c01daf599ec5f8',
    messagingSenderId: '605318797673',
    projectId: 'to-do-list-82f31',
    storageBucket: 'to-do-list-82f31.appspot.com',
    iosBundleId: 'com.example.toDoApp.RunnerTests',
  );
}
